name: Deploy to Share Hosting

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/monarsh
          chmod 600 ~/.ssh/monarsh
          ssh-keyscan -p 21098 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Prepare .env file
        run: |
          echo "APP_ENV=production" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          # Add other necessary env variables

      - name: Deploy Application
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          scp -i ~/.ssh/monarsh -P 21098 .env $SSH_USER@$SSH_HOST:$DEPLOY_PATH/.env
          ssh -i ~/.ssh/monarsh -p 21098 $SSH_USER@$SSH_HOST << 'EOF'
            cd $DEPLOY_PATH || exit 1
            git pull origin master
            composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
            php artisan route:clear
            php artisan migrate:fresh --force
            php artisan db:seed --force
            php artisan storage:link
            # Only cache after everything works
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF