name: Deploy to Shared Hosting

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/monarsh
          chmod 600 ~/.ssh/monarsh
          ssh-keyscan -p 21098 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Copy env
        run: cp .env.example .env

      - name: Install dependencies
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Set file cache driver temporarily
        run: echo "CACHE_DRIVER=file" >> .env

      - name: Clear and cache config
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache

      - name: Test DB via CLI
        run: mysql -h $DB_HOST -P $DB_PORT -u $DB_USERNAME -p"$DB_PASSWORD" $DB_DATABASE -e "SHOW TABLES;"

      - name: Run migrations and seeders
        run: |
          php artisan migrate:fresh --force
          php artisan db:seed --force


      - name: Deploy Application
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          ssh -i ~/.ssh/monarsh -p 21098 $SSH_USER@$SSH_HOST << 'EOF'
            cd $DEPLOY_PATH || exit 1
            git pull origin master
            composer install
            php artisan migrate:fresh --force
            php artisan db:seed --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF

